version: '3.8'

services:
  container_soccer_match_stats_api:
    container_name: container_soccer_match_stats_api
    image: container_soccer_match_stats_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - database

  database:
    container_name: container_soccer_match_stats_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      -  MYSQL_PASSWORD=password
      - MYSQL_DATABASE=soccer_match_stats_db
    restart: always
    platform: linux/amd64
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db-data:
    driver: local
